language: node_js
node_js:
    - node
cache: npm
script: npm run build
addons:
    ssh_known_hosts: ootplandomizer.com
before_deploy:
    - openssl aes-256-cbc -K $encrypted_39c383b172e0_key -iv $encrypted_39c383b172e0_iv
        -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    - echo 'ootplandomizer.com' >> $HOME/.ssh/known_hosts
deploy:
    provider: script
    skip_cleanup: true
    script: ssh root@ootplandomizer.com "rm -rf /var/www/html/static /var/www/html/index.html"; scp -r dist/* root@ootplandomizer.com:/var/www/html
    on:
        branch: master
