const items = [];items.push(new Item("Arrows (10)", 0));
items.push(new Item("Arrows (30)", 1));
items.push(new Item("Arrows (5)", 2));
items.push(new Item("Biggoron Sword", 3));
items.push(new Item("Bolero of Fire", 4));
items.push(new Item("Bomb Bag", 5));
items.push(new Item("Bombchus (10)", 6));
items.push(new Item("Bombchus (20)", 7));
items.push(new Item("Bombchus (5)", 8));
items.push(new Item("Bombs (10)", 9));
items.push(new Item("Bombs (20)", 10));
items.push(new Item("Bombs (5)", 11));
items.push(new Item("Boomerang", 12));
items.push(new Item("Bottle with Letter", 13));
items.push(new Item("Bottle with Milk", 14));
items.push(new Item("Bottle", 15));
items.push(new Item("Bow", 16));
items.push(new Item("Deku Nut Capacity", 17));
items.push(new Item("Deku Nuts (10)", 18));
items.push(new Item("Deku Nuts (5)", 19));
items.push(new Item("Deku Shield", 20));
items.push(new Item("Deku Stick Capacity", 21));
items.push(new Item("Dins Fire", 22));
items.push(new Item("Double Defense", 23));
items.push(new Item("Eponas Song", 24));
items.push(new Item("Farores Wind", 25));
items.push(new Item("Fire Arrows", 26));
items.push(new Item("Goron Tunic", 27));
items.push(new Item("Hammer", 28));
items.push(new Item("Heart Container", 29));
items.push(new Item("Hover Boots", 30));
items.push(new Item("Hylian Shield", 31));
items.push(new Item("Ice Arrows", 32));
items.push(new Item("Ice Trap", 33));
items.push(new Item("Iron Boots", 34));
items.push(new Item("Kokiri Sword", 35));
items.push(new Item("Lens of Truth", 36));
items.push(new Item("Light Arrows", 37));
items.push(new Item("Magic Meter", 38));
items.push(new Item("Minuet of Forest", 39));
items.push(new Item("Mirror Shield", 40));
items.push(new Item("Nayrus Love", 41));
items.push(new Item("Nocturne of Shadow", 42));
items.push(new Item("Piece of Heart (Treasure Chest Game)", 43));
items.push(new Item("Piece of Heart", 44));
items.push(new Item("Pocket Egg", 45));
items.push(new Item("Prelude of Light", 46));
items.push(new Item("Progressive Hookshot", 47));
items.push(new Item("Progressive Scale", 48));
items.push(new Item("Progressive Strength Upgrade", 49));
items.push(new Item("Progressive Wallet", 50));
items.push(new Item("Recovery Heart", 51));
items.push(new Item("Requiem of Spirit", 52));
items.push(new Item("Rupee (1)", 53));
items.push(new Item("Rupees (20)", 54));
items.push(new Item("Rupees (200)", 55));
items.push(new Item("Rupees (5)", 56));
items.push(new Item("Rupees (50)", 57));
items.push(new Item("Sarias Song", 58));
items.push(new Item("Serenade of Water", 59));
items.push(new Item("Slingshot", 60));
items.push(new Item("Song of Storms", 61));
items.push(new Item("Song of Time", 62));
items.push(new Item("Stone of Agony", 63));
items.push(new Item("Suns Song", 64));
items.push(new Item("Zeldas Lullaby", 65));
items.push(new Item("Zora Tunic", 66));
items.push(new Item("Small Key (Forest Temple)", 67));
items.push(new Item("Small Key (Bottom of the Well)", 68));
items.push(new Item("Small Key (Fire Temple)", 69));
items.push(new Item("Small Key (Water Temple)", 70));
items.push(new Item("Small Key (Shadow Temple)", 71));
items.push(new Item("Small Key (Gerudo Training Grounds)", 72));
items.push(new Item("Small Key (Spirit Temple)", 73));
items.push(new Item("Small Key (Ganons Castle)", 74));
items.push(new Item("Boss Key (Forest Temple)", 75));
items.push(new Item("Boss Key (Fire Temple)", 76));
items.push(new Item("Boss Key (Water Temple)", 77));
items.push(new Item("Boss Key (Shadow Temple)", 78));
items.push(new Item("Boss Key (Spirit Temple)", 79));
items.push(new Item("Boss Key (Ganons Castle)", 80));
items.push(new Item("Map (Deku Tree)", 81));
items.push(new Item("Compass (Deku Tree)", 82));
items.push(new Item("Map (Dodongos Cavern)", 83));
items.push(new Item("Compass (Dodongos Cavern)", 84));
items.push(new Item("Map (Jabu Jabus Belly)", 85));
items.push(new Item("Compass (Jabu Jabus Belly)", 86));
items.push(new Item("Map (Forest Temple)", 87));
items.push(new Item("Compass (Forest Temple)", 88));
items.push(new Item("Map (Bottom of the Well)", 89));
items.push(new Item("Compass (Bottom of the Well)", 90));
items.push(new Item("Map (Fire Temple)", 91));
items.push(new Item("Compass (Fire Temple)", 92));
items.push(new Item("Map (Ice Cavern)", 93));
items.push(new Item("Compass (Ice Cavern)", 94));
items.push(new Item("Map (Water Temple)", 95));
items.push(new Item("Compass (Water Temple)", 96));
items.push(new Item("Map (Shadow Temple)", 97));
items.push(new Item("Compass (Shadow Temple)", 98));
items.push(new Item("Map (Spirit Temple)", 99));
items.push(new Item("Compass (Spirit Temple)", 100));
