export default ['Death Mountain Crater (Bombable Wall)',
	'Death Mountain Crater (Rock Grotto)',
	'Death Mountain Trail (Biggoron)',
	'Death Mountain Trail (Storms Grotto)',
	'Desert Colossus (Spirit Temple)',
	'Dodongos Cavern (Bombable Wall)',
	'Gerudo Valley (Waterfall)',
	'Goron City (Maze)',
	'Goron City (Medigoron)',
	'Graveyard (Shadow Temple)',
	'Hyrule Castle (Malon)',
	'Hyrule Castle (Rock Wall)',
	'Hyrule Castle (Storms Grotto)',
	'Hyrule Field (Castle Moat Grotto)',
	'Hyrule Field (Hammer Grotto)',
	'Hyrule Field (Open Grotto)',
	'Hyrule Field (Rock Grotto)',
	'Kakariko (Potion Grotto)',
	'Kokiri Forest (Deku Tree Left)',
	'Kokiri Forest (Deku Tree Right)',
	'Kokiri Forest (Storms Grotto)',
	'Kokiri Forest (Storms)',
	'Lake Hylia (Lab)',
	'Lake Hylia (Southeast Corner)',
	'Lake Hylia (Southwest Corner)',
	'Lost Woods (Bridge)',
	'Lost Woods (Rock Grotto)',
	'Sacred Forest Meadow (Maze Lower)',
	'Sacred Forest Meadow (Maze Upper)',
	'Sacred Forest Meadow (Saria)',
	'Temple of Time (Left)',
	'Temple of Time (Left-Center)',
	'Temple of Time (Right)',
	'Temple of Time (Right-Center)',
	'Zoras Domain (Mweep)',
	'Zoras Fountain (Fairy)',
	'Zoras Fountain (Jabu)',
	'Zoras River (Open Grotto)',
	'Zoras River (Plateau)',
	'Zoras River (Waterfall)']
