export default {
    "" : "https://ootrandomizer.com/img/hash/none.png",
    "Deku Stick" : "https://ootrandomizer.com/img/hash/Deku Stick.png",
    "Deku Nut" : "https://ootrandomizer.com/img/hash/Deku Nut.png",
    "Bow" : "https://ootrandomizer.com/img/hash/Bow.png",
    "Slingshot" : "https://ootrandomizer.com/img/hash/Slingshot.png",
    "Fairy Ocarina" : "https://ootrandomizer.com/img/hash/Fairy Ocarina.png",
    "Bombchu" : "https://ootrandomizer.com/img/hash/Bombchu.png",
    "Longshot" : "https://ootrandomizer.com/img/hash/Longshot.png",
    "Boomerang" : "https://ootrandomizer.com/img/hash/Boomerang.png",
    "Lens of Truth" : "https://ootrandomizer.com/img/hash/Lens of Truth.png",
    "Beans" : "https://ootrandomizer.com/img/hash/Beans.png",
    "Hammer" : "https://ootrandomizer.com/img/hash/Hammer.png",
    "Bottled Fish" : "https://ootrandomizer.com/img/hash/Bottled Fish.png",
    "Bottled Milk" : "https://ootrandomizer.com/img/hash/Bottled Milk.png",
    "Mask of Truth" : "https://ootrandomizer.com/img/hash/Mask of Truth.png",
    "SOLD OUT" : "https://ootrandomizer.com/img/hash/SOLD OUT.png",
    "Cucco" : "https://ootrandomizer.com/img/hash/Cucco.png",
    "Mushroom" : "https://ootrandomizer.com/img/hash/Mushroom.png",
    "Saw" : "https://ootrandomizer.com/img/hash/Saw.png",
    "Frog" : "https://ootrandomizer.com/img/hash/Frog.png",
    "Master Sword" : "https://ootrandomizer.com/img/hash/Master Sword.png",
    "Mirror Shield" : "https://ootrandomizer.com/img/hash/Mirror Shield.png",
    "Kokiri Tunic" : "https://ootrandomizer.com/img/hash/Kokiri Tunic.png",
    "Hover Boots" : "https://ootrandomizer.com/img/hash/Hover Boots.png",
    "Silver Gauntlets" : "https://ootrandomizer.com/img/hash/Silver Gauntlets.png",
    "Gold Scale" : "https://ootrandomizer.com/img/hash/Gold Scale.png",
    "Stone of Agony" : "https://ootrandomizer.com/img/hash/Stone of Agony.png",
    "Skull Token" : "https://ootrandomizer.com/img/hash/Skull Token.png",
    "Heart Container" : "https://ootrandomizer.com/img/hash/Heart Container.png",
    "Boss Key" : "https://ootrandomizer.com/img/hash/Boss Key.png",
    "Compass" : "https://ootrandomizer.com/img/hash/Compass.png",
    "Map" : "https://ootrandomizer.com/img/hash/Map.png",
    "Big Magic" : "https://ootrandomizer.com/img/hash/Big Magic.png",
}
