export default {
    "Arrows (10)":                          0,
    "Arrows (30)":                          0,
    "Arrows (5)":                           0,
    "Biggoron Sword":                       0,
    "Bolero of Fire":                       0,
    "Bomb Bag":                             0,
    "Bombchus (10)":                        0,
    "Bombchus (20)":                        0,
    "Bombchus (5)":                         0,
    "Bombs (10)":                           0,
    "Bombs (20)":                           0,
    "Bombs (5)":                            0,
    "Boomerang":                            0,
    "Bottle with Big Poe":                  0,
    "Bottle with Bugs":                     0,
    "Bottle with Letter":                   0,
    "Bottle with Poe":                      0,
    "Bow":                                  0,
    "Deku Nut Capacity":                    0,
    "Deku Nuts (10)":                       0,
    "Deku Nuts (5)":                        0,
    "Deku Seeds (30)":                      0,
    "Deku Shield":                          0,
    "Deku Stick (1)":                       0,
    "Deku Stick Capacity":                  0,
    "Dins Fire":                            0,
    "Double Defense":                       0,
    "Eponas Song":                          0,
    "Farores Wind":                         0,
    "Fire Arrows":                          0,
    "Goron Tunic":                          0,
    "Hammer":                               0,
    "Heart Container":                      0,
    "Hover Boots":                          0,
    "Hylian Shield":                        0,
    "Ice Arrows":                           0,
    "Ice Trap":                             0,
    "Iron Boots":                           0,
    "Kokiri Sword":                         0,
    "Lens of Truth":                        0,
    "Light Arrows":                         0,
    "Magic Meter":                          0,
    "Minuet of Forest":                     0,
    "Mirror Shield":                        0,
    "Nayrus Love":                          0,
    "Nocturne of Shadow":                   0,
    "Piece of Heart (Treasure Chest Game)": 0,
    "Piece of Heart":                       0,
    "Prelude of Light":                     0,
    "Prescription":                         0,
    "Progressive Hookshot":                 0,
    "Progressive Scale":                    0,
    "Progressive Strength Upgrade":         0,
    "Progressive Wallet":                   0,
    "Recovery Heart":                       0,
    "Requiem of Spirit":                    0,
    "Rupee (1)":                            0,
    "Rupees (20)":                          0,
    "Rupees (200)":                         0,
    "Rupees (5)":                           0,
    "Rupees (50)":                          0,
    "Sarias Song":                          0,
    "Serenade of Water":                    0,
    "Slingshot":                            0,
    "Song of Storms":                       0,
    "Song of Time":                         0,
    "Stone of Agony":                       0,
    "Suns Song":                            0,
    "Zeldas Lullaby":                       0,
    "Zora Tunic":                           0
}